export const Dentist = {
    name:'Dr Bouzid Hichem',
    aboutImages: [
        '/images/dr3.png',
        '/images/dr8.png',
        '/images/dr9.png',
        '/images/dr10.png',
        '/images/dr11.png',
        '/images/dr1.png',
        '/images/dr5.png',
        '/images/dr4.png',
        '/images/dr2.png',
        '/images/dr7.png',
      ],
      clinicImages: [
          '/images/pd18.png', 
          '/images/pd20.png', 
          '/images/pd6.png', 
          '/images/pd4.png', 
          '/images/pd9.png',
          '/images/pd16.png',
          '/images/pd17.png',
          '/images/pd12.png',
          '/images/pd3.png', 
          '/images/pd7.png',
          '/images/pd5.png', 
          '/images/pd10.png',
          '/images/pd11.png',
          '/images/pd14.png',
          '/images/pd13.png',
          '/images/pd2.png', 
    ],
          location: 'logments berrouaghia, Médéa, Algeria',
    logo:'/images/bouzidLogo2.png',
    navText:'Bienvenue à Clinique Smile Dentaire',
    phone1:'05 52 37 58 11',
    phone2:'+213 552 37 58 11',
    email:'smile.dentaire.bouzid@gmail.com',
    clinicName:'Clinique Smile Dentaire',
    clinicImage:'/images/cdsclinic4.png',
    title:'chirurgie dentaire, Doctor Bouzid',
    description: "Clinique Smile dentaire est un cabinet dentaire moderne et bien équipé, situé à berrouaghia wilaya de Médéa. Nous offrons une gamme complète de services dentaires pour les enfants et les adultes. Nous sommes fiers de fournir des soins dentaires de qualité dans un environnement chaleureux et accueillant.",
}


export const Cases = [
    { id: 1, treatment: "facettes", beforeImage: "/images/before1.jpg", afterImage: "/images/after1.jpg" },
    { id: 2, treatment: "implants", beforeImage: "/images/before2.jpg", afterImage: "/images/after2.jpg" },  
    { id: 3, treatment: "facettes", beforeImage: "/images/before3.jpg", afterImage: "/images/after3.jpg" },
    { id: 4, treatment: "implants", beforeImage: "/images/before4.jpg", afterImage: "/images/after4.jpg" },  
    { id: 5, treatment: "facettes", beforeImage: "/images/before5.jpg", afterImage: "/images/after5.jpg" },
    { id: 6, treatment: "implants", beforeImage: "/images/before6.jpg", afterImage: "/images/after6.jpg" },  
    { id: 7, treatment: "facettes", beforeImage: "/images/before7.jpg", afterImage: "/images/after7.jpg" },
    { id: 8, treatment: "implants", beforeImage: "/images/before8.jpg", afterImage: "/images/after8.jpg" },  
    { id: 9, treatment: "facettes", beforeImage: "/images/before9.jpg", afterImage: "/images/after9.jpg" },
    { id: 10, treatment: "implants", beforeImage: "/images/before10.jpg", afterImage: "/images/after10.jpg" },  
    { id: 11, treatment: "facettes", beforeImage: "/images/before11.jpg", afterImage: "/images/after11.jpg" },
    { id: 12, treatment: "implants", beforeImage: "/images/before12.jpg", afterImage: "/images/after12.jpg" },  
    { id: 13, treatment: "facettes", beforeImage: "/images/before13.jpg", afterImage: "/images/after13.jpg" },
    { id: 14, treatment: "implants", beforeImage: "/images/before14.jpg", afterImage: "/images/after14.jpg" },  
    { id: 15, treatment: "facettes", beforeImage: "/images/before15.jpg", afterImage: "/images/after15.jpg" },
    { id: 16, treatment: "implants", beforeImage: "/images/before16.jpg", afterImage: "/images/after16.jpg" },  
    { id: 17, treatment: "facettes", beforeImage: "/images/before17.jpg", afterImage: "/images/after17.jpg" },
    { id: 18, treatment: "implants", beforeImage: "/images/before18.jpg", afterImage: "/images/after18.jpg" },  
    { id: 19, treatment: "facettes", beforeImage: "/images/before19.jpg", afterImage: "/images/after19.jpg" },
    { id: 20, treatment: "implants", beforeImage: "/images/before20.jpg", afterImage: "/images/after20.jpg" },  
    { id: 21, treatment: "facettes", beforeImage: "/images/before21.jpg", afterImage: "/images/after21.jpg" },
    { id: 22, treatment: "facettes", beforeImage: "/images/before22.jpg", afterImage: "/images/after22.jpg" },
    { id: 23, treatment: "facettes", beforeImage: "/images/before23.jpg", afterImage: "/images/after23.jpg" },
    { id: 24, treatment: "facettes", beforeImage: "/images/before24.jpg", afterImage: "/images/after24.jpg" },
    { id: 25, treatment: "facettes", beforeImage: "/images/before25.jpg", afterImage: "/images/after25.jpg" },
    { id: 26, treatment: "facettes", beforeImage: "/images/before26.jpg", afterImage: "/images/after26.jpg" },
    { id: 27, treatment: "facettes", beforeImage: "/images/before27.jpg", afterImage: "/images/after27.jpg" },
    { id: 28, treatment: "facettes", beforeImage: "/images/before28.jpg", afterImage: "/images/after28.jpg" },
    { id: 29, treatment: "facettes", beforeImage: "/images/before29.jpg", afterImage: "/images/after29.jpg" },
    { id: 30, treatment: "facettes", beforeImage: "/images/before30.jpg", afterImage: "/images/after30.jpg" },
    { id: 31, treatment: "facettes", beforeImage: "/images/before31.jpg", afterImage: "/images/after31.jpg" },
    { id: 32, treatment: "facettes", beforeImage: "/images/before32.jpg", afterImage: "/images/after32.jpg" },
    { id: 33, treatment: "facettes", beforeImage: "/images/before33.jpg", afterImage: "/images/after33.jpg" },
    { id: 34, treatment: "facettes", beforeImage: "/images/before34.jpg", afterImage: "/images/after34.jpg" },
    { id: 35, treatment: "facettes", beforeImage: "/images/before35.jpg", afterImage: "/images/after35.jpg" },
    { id: 36, treatment: "facettes", beforeImage: "/images/before36.jpg", afterImage: "/images/after36.jpg" },
    { id: 37, treatment: "facettes", beforeImage: "/images/before37.jpg", afterImage: "/images/after37.jpg" },
]